## ------------------------------------------------------------------------- ##
## Script to calculate pairwise technology similarity between firms by vectors#
## generated by doc2vec                                                      ##
## We take pairwise tech similarity in 1980 as an example, similarities in   ##
## other years could be calculated in the same way.                          ##
##                                                                           ##
## "Measuring the Position and Differentiation of Firms in                   ##
##  Technology Space" -- Sam Arts, Bruno Cassiman, and Jianan Hou            ##
##                                                                           ##
##                                                                           ##
## ------------------------------------------------------------------------- ##

library(readr)
library(Matrix)
library(janitor)
library(plyr)
library(tidyr)
library(quanteda)
library(lsa)
library(Rcpp)
library(matlab)
library(tilting)
library(tidyverse)

# Set working directory
setwd("./data/")

# Import patent vectors and patent portfolio data
# "patents_vectors" is the output of doc2vec_training which summarizes each patent as a vector of 700 dimensions. 
vectors <- read_csv("./data/patents_vectors.csv")

# "patent_portfolio" is compiled based on the "patent-gvkey" linkages developed by Arora et al. (2021) (see 
# https://zenodo.org/record/3594743). For each firm i in year t, it documents patents contained in the portfolio (with filing years between t-5
# and t-1). The file contains one row and three columns for each "gvkey-patent" linkage. The first column contains gvkey, the second column contains year, and third column contains patent number. 
patent_portfolio <- read_csv("./data/patent_portfolio.csv")

# Load 1980 technology similarity data and remove unnecessary columns
simi_1980 <- read_csv("./simi_1980_tfidf.csv")
simi_1980$similarity_tfidf <- NULL

# Subset patent portfolio for the year 1980
p1980 <- subset(patent_portfolio, year == 1980)

# Merge 1980 patent portfolio with vectors
p1980_vectors <- merge(x = p1980, y = vectors, by = "patent", all = FALSE)

# Calculate the average of vectors at firm level (drop unnecessary columns)
p1980$patent <- p1980$year <- p1980$conm <- NULL
mean_1980 <- p1980 %>%
  group_by(gvkey) %>%
  summarise_all(mean)

# Convert the data frame to a matrix
mean_1980 <- mean_1980[order(mean_1981$gvkey), ]
text.matrix <- data.matrix(mean_1980[, 2:701])

# Calculate pairwise similarity
ptm <- proc.time()
A <- t(text.matrix)
normA <- col.norm(A)
A <- sweep(A, 2, normA, FUN = '/')

# Create a placeholder for cosine similarity
B <- A
n <- dim(B)[2]
cos.out <- matrix(0, n, n)

# Compute the cosine similarity
for (j in 2:(n - 1)) {
  B <- B[, c(2:n, 1)]
  cos.out[, j] <- colSums(A * B)
  if (j %% 200 == 0) {
    print(j)
  }
}

cos.out <- t(cos.out)
cosine_similarity_vector <- cos.out[!fliplr(lower.tri(cos.out, diag = TRUE))]
proc.time() - ptm

# Add cosine similarity to the similarity data frame
simi_1980$similarity_doc2vec <- cosine_similarity_vector

# Export to a CSV file
write.csv(simi_1980, file = "./data/simi_1980_doc2vec.csv")

  
